# Generated by Django 3.2.3 on 2021-06-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_nota', models.CharField(max_length=50, verbose_name='Nombre Nota')),
                ('descripcion_nota', models.CharField(max_length=200, verbose_name='Descripcion de la Nota')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion de la nota')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha fin de la nota')),
                ('estado_nota', models.CharField(max_length=30, verbose_name='Estado de la nota Vigente / Vencida / Completada')),
            ],
        ),
    ]
